name: SkillsMC
version: ${project.version}
main: ragnaorok.Main.Main
api-version: 1.19
authors: [ Ragnaorok ]
description: 1.19 Paper Plugin
commands:
  profile:
    description: show profile
    usage: /<command>
  el:
    description: test
    usage: /<command>
  class:
    description: select a class
    usage: /<command>
  souls:
    description: a currency command
  saveAll:
    description: a save command
    usage: /<command>
  kaboom:
    description: blow up
    usage: /<command>
  reinforce:
    description: enchants shields
    usage: /<command>
  check:
    description: check enchants
    usage: /<command>
