name: SkillsMC
version: ${project.version}
main: ragnaorok.Main.Main
api-version: 1.21
authors: [ Ragnaorok ]
description: 1.21 Paper Plugin
commands:
  profile:
    description: show profile
    usage: /<command>
  guide:
    description: gives guidebook
    usage: /<command>
  class:
    description: select a class
    usage: /<command>
  souls:
    description: a currency command
  saveAll:
    description: a save command
    usage: /<command>
  kaboom:
    description: blow up
    usage: /<command>
  reinforce:
    description: enchants shields
    usage: /<command>
  check:
    description: check enchants
    usage: /<command>
  setlevel:
    description: Set the level of a player
    usage: /setlevel <player> <level>
